// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type PGLink = prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

export interface HeroSliceDefaultPrimary {
	eyebrow: prismic.KeyTextField;
	title_white: prismic.KeyTextField;
	title_gold: prismic.KeyTextField;
	description: prismic.RichTextField;
	background_image: prismic.ImageField<never>;
	primary_cta: PGLink;
	secondary_cta: PGLink;
	section_id: prismic.KeyTextField;
}
export type HeroSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<HeroSliceDefaultPrimary>,
	never
>;
type HeroSliceVariation = HeroSliceDefault;
export type HeroSlice = prismic.SharedSlice<"Hero", HeroSliceVariation>;

export interface StoryStatsSliceDefaultPrimary {
	eyebrow: prismic.KeyTextField;
	title_lead: prismic.KeyTextField;
	title_highlight: prismic.KeyTextField;
	intro: prismic.RichTextField;
	section_id: prismic.KeyTextField;
}
export interface StoryStatsSliceDefaultItem {
	icon: prismic.SelectField<"calendar" | "globe" | "users" | "trophy">;
	stat_value: prismic.KeyTextField;
	stat_label: prismic.KeyTextField;
}
export type StoryStatsSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<StoryStatsSliceDefaultPrimary>,
	Simplify<StoryStatsSliceDefaultItem>
>;
type StoryStatsSliceVariation = StoryStatsSliceDefault;
export type StoryStatsSlice = prismic.SharedSlice<"StoryStats", StoryStatsSliceVariation>;

export interface SportsGridSliceDefaultPrimary {
	eyebrow: prismic.KeyTextField;
	title_white: prismic.KeyTextField;
	title_gold: prismic.KeyTextField;
	section_id: prismic.KeyTextField;
}
export interface SportsGridSliceDefaultItem {
	sport_name: prismic.KeyTextField;
	description: prismic.RichTextField;
	category_badge: prismic.KeyTextField;
	accent: prismic.SelectField<"blue" | "gold" | "green">;
}
export type SportsGridSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<SportsGridSliceDefaultPrimary>,
	Simplify<SportsGridSliceDefaultItem>
>;
type SportsGridSliceVariation = SportsGridSliceDefault;
export type SportsGridSlice = prismic.SharedSlice<"SportsGrid", SportsGridSliceVariation>;

export interface TrainingLocationsSliceDefaultPrimary {
	eyebrow: prismic.KeyTextField;
	title_gold: prismic.KeyTextField;
	title_white: prismic.KeyTextField;
	intro: prismic.RichTextField;
	section_id: prismic.KeyTextField;
}
export interface TrainingLocationsSliceDefaultItem {
	venue_name: prismic.KeyTextField;
	sports_line: prismic.KeyTextField;
	address: prismic.KeyTextField;
	transport: prismic.KeyTextField;
	schedule: prismic.KeyTextField;
}
export type TrainingLocationsSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<TrainingLocationsSliceDefaultPrimary>,
	Simplify<TrainingLocationsSliceDefaultItem>
>;
type TrainingLocationsSliceVariation = TrainingLocationsSliceDefault;
export type TrainingLocationsSlice = prismic.SharedSlice<
	"TrainingLocations",
	TrainingLocationsSliceVariation
>;

export interface NewsShowcaseSliceDefaultPrimary {
	feed: prismic.SelectField<"manual" | "latest_articles">;
	eyebrow: prismic.KeyTextField;
	title_white: prismic.KeyTextField;
	title_gold: prismic.KeyTextField;
	section_id: prismic.KeyTextField;
}
export interface NewsShowcaseSliceDefaultItem {
	category: prismic.KeyTextField;
	date_display: prismic.KeyTextField;
	headline: prismic.KeyTextField;
	summary: prismic.KeyTextField;
	link: PGLink;
}
export type NewsShowcaseSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<NewsShowcaseSliceDefaultPrimary>,
	Simplify<NewsShowcaseSliceDefaultItem>
>;
type NewsShowcaseSliceVariation = NewsShowcaseSliceDefault;
export type NewsShowcaseSlice = prismic.SharedSlice<
	"NewsShowcase",
	NewsShowcaseSliceVariation
>;

export interface JoinBandSliceDefaultPrimary {
	eyebrow: prismic.KeyTextField;
	title_gold: prismic.KeyTextField;
	title_white: prismic.KeyTextField;
	description: prismic.RichTextField;
	contact_link: PGLink;
	section_id: prismic.KeyTextField;
}
export type JoinBandSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<JoinBandSliceDefaultPrimary>,
	never
>;
type JoinBandSliceVariation = JoinBandSliceDefault;
export type JoinBandSlice = prismic.SharedSlice<"JoinBand", JoinBandSliceVariation>;

export interface CallToActionSliceDefaultPrimary {
	heading: prismic.KeyTextField;
	description: prismic.RichTextField;
	cta: prismic.Repeatable<PGLink>;
}
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<CallToActionSliceDefaultPrimary>,
	never
>;
type CallToActionSliceVariation = CallToActionSliceDefault;
export type CallToActionSlice = prismic.SharedSlice<"CallToAction", CallToActionSliceVariation>;

export interface ImageHighlightSliceDefaultPrimary {
	image: prismic.ImageField<never>;
	caption: prismic.RichTextField;
}
export type ImageHighlightSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<ImageHighlightSliceDefaultPrimary>,
	never
>;
type ImageHighlightSliceVariation = ImageHighlightSliceDefault;
export type ImageHighlightSlice = prismic.SharedSlice<
	"ImageHighlight",
	ImageHighlightSliceVariation
>;

export interface TextBlockSliceDefaultPrimary {
	body: prismic.RichTextField;
}
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<TextBlockSliceDefaultPrimary>,
	never
>;
type TextBlockSliceVariation = TextBlockSliceDefault;
export type TextBlockSlice = prismic.SharedSlice<"TextBlock", TextBlockSliceVariation>;

type ArticleDocumentDataSlicesSlice = TextBlockSlice | ImageHighlightSlice | CallToActionSlice

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
	/**
	 * Publication date field in *Article*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.publication_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/timestamp
	 */
	publication_date: prismic.TimestampField;
	
	/**
	 * Featured image field in *Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	featured_image: prismic.ImageField<never>;
	
	/**
	 * Excerpt field in *Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.excerpt
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	excerpt: prismic.KeyTextField;
	
	/**
	 * Translation group id field in *Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.translation_group_id
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	translation_group_id: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Article*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: article.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: article.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, "article", Lang>;

type LandingPageDocumentDataSlicesSlice = HeroSlice | StoryStatsSlice | SportsGridSlice | TrainingLocationsSlice | NewsShowcaseSlice | JoinBandSlice | TextBlockSlice | ImageHighlightSlice | CallToActionSlice

/**
 * Content for Landing page documents
 */
interface LandingPageDocumentData {
	/**
	 * Page kind field in *Landing page*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.page_kind
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	page_kind: prismic.SelectField<"home" | "training" | "calendar" | "contact" | "sitemap" | "other">;
	
	/**
	 * Featured image field in *Landing page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	featured_image: prismic.ImageField<never>;
	
	/**
	 * Translation group id field in *Landing page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Polylang pll_* group slug from WordPress
	 * - **API ID Path**: landing_page.translation_group_id
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	translation_group_id: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Landing page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Landing page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: landing_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Landing page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: landing_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Landing page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<LandingPageDocumentData>, "landing_page", Lang>;

/**
 * Content for Site settings documents
 */
interface SiteSettingsDocumentData {
	/**
	 * Club tagline field in *Site settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.club_tagline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	club_tagline: prismic.KeyTextField;
	
	/**
	 * Header banner image field in *Site settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.header_banner
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	header_banner: prismic.ImageField<never>;/**
	 * Primary navigation field in *Site settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.primary_navigation
	 * - **Tab**: Navigation
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	primary_navigation: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>;
	
	/**
	 * Social and external links field in *Site settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.social_links
	 * - **Tab**: Navigation
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_links: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>;
	
	/**
	 * Footer links field in *Site settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.footer_links
	 * - **Tab**: Navigation
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	footer_links: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>;
}

/**
 * Site settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SiteSettingsDocumentData>, "site_settings", Lang>;

export type AllDocumentTypes = ArticleDocument | LandingPageDocument | SiteSettingsDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			ArticleDocument,
			ArticleDocumentData,
			ArticleDocumentDataSlicesSlice,
			LandingPageDocument,
			LandingPageDocumentData,
			LandingPageDocumentDataSlicesSlice,
			SiteSettingsDocument,
			SiteSettingsDocumentData,
			AllDocumentTypes,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceDefault,
			StoryStatsSlice,
			StoryStatsSliceDefaultPrimary,
			StoryStatsSliceDefaultItem,
			StoryStatsSliceDefault,
			SportsGridSlice,
			SportsGridSliceDefaultPrimary,
			SportsGridSliceDefaultItem,
			SportsGridSliceDefault,
			TrainingLocationsSlice,
			TrainingLocationsSliceDefaultPrimary,
			TrainingLocationsSliceDefaultItem,
			TrainingLocationsSliceDefault,
			NewsShowcaseSlice,
			NewsShowcaseSliceDefaultPrimary,
			NewsShowcaseSliceDefaultItem,
			NewsShowcaseSliceDefault,
			JoinBandSlice,
			JoinBandSliceDefaultPrimary,
			JoinBandSliceDefault,
			CallToActionSlice,
			CallToActionSliceDefaultPrimary,
			CallToActionSliceDefault,
			ImageHighlightSlice,
			ImageHighlightSliceDefaultPrimary,
			ImageHighlightSliceDefault,
			TextBlockSlice,
			TextBlockSliceDefaultPrimary,
			TextBlockSliceDefault
		}
	}
}