// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ArticleDocumentDataSlicesSlice =
  | TextBlockSlice
  | ImageHighlightSlice
  | CallToActionSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Publication date field in *Article*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: article.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  publication_date: prismic.TimestampField;

  /**
   * Featured image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Excerpt field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Translation group id field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.translation_group_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  translation_group_id: prismic.KeyTextField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice =
  | HeroSlice
  | StoryStatsSlice
  | SportsGridSlice
  | TrainingLocationsSlice
  | NewsShowcaseSlice
  | JoinBandSlice
  | TextBlockSlice
  | ImageHighlightSlice
  | CallToActionSlice;

/**
 * Content for Landing page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Content for Site settings documents
 */
interface SiteSettingsDocumentData {
  /**
   * Club tagline field in *Site settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.club_tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  club_tagline: prismic.KeyTextField;

  /**
   * Header banner image field in *Site settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.header_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_banner: prismic.ImageField<never>; /**
   * Primary navigation field in *Site settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.primary_navigation
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_navigation: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Social and external links field in *Site settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.social_links
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Footer links field in *Site settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.footer_links
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Site settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteSettingsDocumentData>,
    "site_settings",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | LandingPageDocument
  | SiteSettingsDocument;

/**
 * Primary content in *Call to action → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *Call to action → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: CallToAction.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Call to action → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: CallToAction.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Calls to action field in *Call to action → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: CallToAction.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for Call to action Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Call to action*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * Call to action Shared Slice
 *
 * - **API ID**: `CallToAction`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<
  "CallToAction",
  CallToActionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title (white) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.title_white
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_white: prismic.KeyTextField;

  /**
   * Title (gold) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.title_gold
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_gold: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Primary CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Section anchor id field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: hero
   * - **API ID Path**: Hero.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `Hero`
 * - **Description**: Full-viewport hero with background image and dual CTAs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"Hero", HeroSliceVariation>;

/**
 * Primary content in *Image highlight → Default → Primary*
 */
export interface ImageHighlightSliceDefaultPrimary {
  /**
   * Image field in *Image highlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ImageHighlight.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image highlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ImageHighlight.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for Image highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image highlight*
 */
type ImageHighlightSliceVariation = ImageHighlightSliceDefault;

/**
 * Image highlight Shared Slice
 *
 * - **API ID**: `ImageHighlight`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageHighlightSlice = prismic.SharedSlice<
  "ImageHighlight",
  ImageHighlightSliceVariation
>;

/**
 * Primary content in *Join band → Default → Primary*
 */
export interface JoinBandSliceDefaultPrimary {
  /**
   * Eyebrow field in *Join band → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: JoinBand.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title (gold) field in *Join band → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: JoinBand.default.primary.title_gold
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_gold: prismic.KeyTextField;

  /**
   * Title (white) field in *Join band → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: JoinBand.default.primary.title_white
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_white: prismic.KeyTextField;

  /**
   * Description field in *Join band → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: JoinBand.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Contact / primary button field in *Join band → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: JoinBand.default.primary.contact_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Section anchor id field in *Join band → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: join
   * - **API ID Path**: JoinBand.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Default variation for Join band Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JoinBandSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JoinBandSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Join band*
 */
type JoinBandSliceVariation = JoinBandSliceDefault;

/**
 * Join band Shared Slice
 *
 * - **API ID**: `JoinBand`
 * - **Description**: Get involved CTA with contact link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JoinBandSlice = prismic.SharedSlice<
  "JoinBand",
  JoinBandSliceVariation
>;

/**
 * Primary content in *News showcase → Default → Primary*
 */
export interface NewsShowcaseSliceDefaultPrimary {
  /**
   * Content source field in *News showcase → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: manual
   * - **API ID Path**: NewsShowcase.default.primary.feed
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  feed: prismic.SelectField<"manual" | "latest_articles", "filled">;

  /**
   * Eyebrow field in *News showcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title (white) field in *News showcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.default.primary.title_white
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_white: prismic.KeyTextField;

  /**
   * Title (gold) field in *News showcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.default.primary.title_gold
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_gold: prismic.KeyTextField;

  /**
   * Section anchor id field in *News showcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: news
   * - **API ID Path**: NewsShowcase.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * View all news — button label field in *News showcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. View all news / Toutes les actualités
   * - **API ID Path**: NewsShowcase.default.primary.view_all_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  view_all_label: prismic.KeyTextField;
}

/**
 * Primary content in *News showcase → Items*
 */
export interface NewsShowcaseSliceDefaultItem {
  /**
   * Category badge field in *News showcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.items[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Date display field in *News showcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.items[].date_display
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_display: prismic.KeyTextField;

  /**
   * Headline field in *News showcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.items[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Summary field in *News showcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.items[].summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  summary: prismic.KeyTextField;

  /**
   * Link field in *News showcase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: NewsShowcase.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for News showcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsShowcaseSliceDefaultPrimary>,
  Simplify<NewsShowcaseSliceDefaultItem>
>;

/**
 * Slice variation for *News showcase*
 */
type NewsShowcaseSliceVariation = NewsShowcaseSliceDefault;

/**
 * News showcase Shared Slice
 *
 * - **API ID**: `NewsShowcase`
 * - **Description**: Club news cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsShowcaseSlice = prismic.SharedSlice<
  "NewsShowcase",
  NewsShowcaseSliceVariation
>;

/**
 * Primary content in *Sports grid → Default → Primary*
 */
export interface SportsGridSliceDefaultPrimary {
  /**
   * Eyebrow field in *Sports grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: SportsGrid.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Sports grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: SportsGrid.default.primary.title_white
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_white: prismic.KeyTextField;

  /**
   * Title field in *Sports grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: SportsGrid.default.primary.title_gold
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_gold: prismic.KeyTextField;

  /**
   * Section anchor id field in *Sports grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: sports
   * - **API ID Path**: SportsGrid.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *Sports grid → Items*
 */
export interface SportsGridSliceDefaultItem {
  /**
   * Sport name field in *Sports grid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: SportsGrid.items[].sport_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sport_name: prismic.KeyTextField;

  /**
   * Description field in *Sports grid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: SportsGrid.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Category badge field in *Sports grid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: SportsGrid.items[].category_badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_badge: prismic.KeyTextField;

  /**
   * Accent bar field in *Sports grid → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: blue
   * - **API ID Path**: SportsGrid.items[].accent
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  accent: prismic.SelectField<"blue" | "red", "filled">;
}

/**
 * Default variation for Sports grid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SportsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SportsGridSliceDefaultPrimary>,
  Simplify<SportsGridSliceDefaultItem>
>;

/**
 * Slice variation for *Sports grid*
 */
type SportsGridSliceVariation = SportsGridSliceDefault;

/**
 * Sports grid Shared Slice
 *
 * - **API ID**: `SportsGrid`
 * - **Description**: Grid of sport cards with accent bar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SportsGridSlice = prismic.SharedSlice<
  "SportsGrid",
  SportsGridSliceVariation
>;

/**
 * Primary content in *Story & stats → Default → Primary*
 */
export interface StoryStatsSliceDefaultPrimary {
  /**
   * Eyebrow field in *Story & stats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: StoryStats.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title (white) field in *Story & stats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: StoryStats.default.primary.title_lead
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_lead: prismic.KeyTextField;

  /**
   * Title highlight (gold) field in *Story & stats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: StoryStats.default.primary.title_highlight
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_highlight: prismic.KeyTextField;

  /**
   * Intro field in *Story & stats → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: StoryStats.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Section anchor id field in *Story & stats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: about
   * - **API ID Path**: StoryStats.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *Story & stats → Items*
 */
export interface StoryStatsSliceDefaultItem {
  /**
   * Icon field in *Story & stats → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: calendar
   * - **API ID Path**: StoryStats.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "calendar" | "globe" | "users" | "trophy",
    "filled"
  >;

  /**
   * Value field in *Story & stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: StoryStats.items[].stat_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_value: prismic.KeyTextField;

  /**
   * Label field in *Story & stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: StoryStats.items[].stat_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_label: prismic.KeyTextField;
}

/**
 * Default variation for Story & stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StoryStatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StoryStatsSliceDefaultPrimary>,
  Simplify<StoryStatsSliceDefaultItem>
>;

/**
 * Slice variation for *Story & stats*
 */
type StoryStatsSliceVariation = StoryStatsSliceDefault;

/**
 * Story & stats Shared Slice
 *
 * - **API ID**: `StoryStats`
 * - **Description**: Eyebrow, split headline, intro, and stat cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StoryStatsSlice = prismic.SharedSlice<
  "StoryStats",
  StoryStatsSliceVariation
>;

/**
 * Primary content in *Text block → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Body field in *Text block → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TextBlock.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Text block Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text block*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * Text block Shared Slice
 *
 * - **API ID**: `TextBlock`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<
  "TextBlock",
  TextBlockSliceVariation
>;

/**
 * Primary content in *Training locations → Default → Primary*
 */
export interface TrainingLocationsSliceDefaultPrimary {
  /**
   * Eyebrow field in *Training locations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title (gold) field in *Training locations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.default.primary.title_gold
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_gold: prismic.KeyTextField;

  /**
   * Title (white) field in *Training locations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.default.primary.title_white
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_white: prismic.KeyTextField;

  /**
   * Intro field in *Training locations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Section anchor id field in *Training locations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: training
   * - **API ID Path**: TrainingLocations.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *Training locations → Items*
 */
export interface TrainingLocationsSliceDefaultItem {
  /**
   * Venue name field in *Training locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.items[].venue_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  venue_name: prismic.KeyTextField;

  /**
   * Sports (subtitle) field in *Training locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.items[].sports_line
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sports_line: prismic.KeyTextField;

  /**
   * Address field in *Training locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.items[].address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Public transport field in *Training locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.items[].transport
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  transport: prismic.KeyTextField;

  /**
   * Schedule field in *Training locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: TrainingLocations.items[].schedule
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  schedule: prismic.KeyTextField;

  /**
   * Maps Link field in *Training locations → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add the Google map link here
   * - **API ID Path**: TrainingLocations.items[].maps_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  maps_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Training locations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrainingLocationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrainingLocationsSliceDefaultPrimary>,
  Simplify<TrainingLocationsSliceDefaultItem>
>;

/**
 * Slice variation for *Training locations*
 */
type TrainingLocationsSliceVariation = TrainingLocationsSliceDefault;

/**
 * Training locations Shared Slice
 *
 * - **API ID**: `TrainingLocations`
 * - **Description**: Where and when training happens
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrainingLocationsSlice = prismic.SharedSlice<
  "TrainingLocations",
  TrainingLocationsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      SiteSettingsDocument,
      SiteSettingsDocumentData,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageHighlightSlice,
      ImageHighlightSliceDefaultPrimary,
      ImageHighlightSliceVariation,
      ImageHighlightSliceDefault,
      JoinBandSlice,
      JoinBandSliceDefaultPrimary,
      JoinBandSliceVariation,
      JoinBandSliceDefault,
      NewsShowcaseSlice,
      NewsShowcaseSliceDefaultPrimary,
      NewsShowcaseSliceDefaultItem,
      NewsShowcaseSliceVariation,
      NewsShowcaseSliceDefault,
      SportsGridSlice,
      SportsGridSliceDefaultPrimary,
      SportsGridSliceDefaultItem,
      SportsGridSliceVariation,
      SportsGridSliceDefault,
      StoryStatsSlice,
      StoryStatsSliceDefaultPrimary,
      StoryStatsSliceDefaultItem,
      StoryStatsSliceVariation,
      StoryStatsSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TrainingLocationsSlice,
      TrainingLocationsSliceDefaultPrimary,
      TrainingLocationsSliceDefaultItem,
      TrainingLocationsSliceVariation,
      TrainingLocationsSliceDefault,
    };
  }
}
